---
title: "Homework #2 - MATH 261A"
author: "Noah Arias"
format:
    pdf:
        include-in-header:
        - text: |
            \usepackage{amsmath}
            \usepackage{tcolorbox}
---

## Problem 1
We assume that $X_1, X_2, \dots , X_n \sim N(\mu, \sigma^2)$ and are I.I.D.

# Part (a)
We know that $\bar{X}_n$ follows a Gaussian distribution, but we must determine the mean and variance paramters.

We do this by a straightforward expectation and variance calculation:

$$
\begin{aligned}
E(\bar{X}_n) = E\Bigg(\frac{\sum_{i=1}^n X_i}{n}\Bigg) = \frac{1}{n}\sum_{i=1}^n E(X_i)
\end{aligned}
$$

Since each $X_i$ follows a $N(\mu, \sigma^2)$, it's mean is simply $\mu$. Therefore, we can rewrite the last sum in the above calculation as:

$$
\begin{aligned}
\frac{1}{n}\sum_{i=1}^n E(X_i) = \frac{1}{n}\sum_{i=1}^n \mu = \frac{\mu \cdot n}{n} = \mu
\end{aligned}
$$

Therefore, we now know that the expection of $\bar{X}_n$ is $\mu$.

Now we calculate it's variance in a similar manner:

$$
\begin{aligned}
\text{Var}(\bar{X}_n) = \text{Var}\Bigg(\frac{\sum_{i=1}^n X_i}{n}\Bigg) = \frac{1}{n^2}\sum_{i=1}^n \text{Var}(X_i)
\end{aligned}
$$

We note that the third equality is valid because since the $X_i$ are *independent* as well as identially distributed. This means that any and all covariance terms areo precisely zero. Continuing the calculation, we arrive at:

$$
\begin{aligned}
\frac{1}{n^2}\sum_{i=1}^n \text{Var}(X_i) = \frac{1}{n^2}\sum_{i=1}^n \sigma^2 = \frac{\sigma^2 \cdot n}{n^2} = \frac{\sigma^2}{n}
\end{aligned}
$$

With this result, we can finally conclude that $\color{red}\boxed{\color{black} \bar{X}_n \sim N(\mu, \frac{\sigma^2}{n})}$.

# Part (b)
The general structure of a confidence interval is following:

$$
\begin{aligned}
(\text{point estimate } \pm \text{ critical value } \cdot \text{ standard deviation/error})
\end{aligned}
$$

We are specifically deriving a 95% confidence interval for the sampling distribution of $\bar{X}_n$ which we now know is $N(\mu, \frac{\sigma^2}{n})$.

The first thing we recognize is that $\mu$ is the parameter, whose location we are trying to ascertain with the estimate $\bar{X}_n$, for a given sample of size $n$. Thus, the point estimate for $\mu$ is $\bar{X}_n$.

Secondly, we must determine the critical value. This is dependent on the sampling distribution which is $N(\mu, \frac{\sigma^2}{n})$. Since we know not only our distribution is Normal but the population variance too, our a critical value is a z-score with form:

$$
z_{\text{crit}} = \frac{\bar{x}_n - \mu}{\sigma/\sqrt{n}}
$$

This expression follows a standard Normal distribution $N(0,1)$.

The standard error is easy to find as it is simply $\frac{\sigma}{\sqrt{n}}$.

Starting at the requirement that for a 95% confidence interval, the following must be true:

$$
P(-1.96 < \frac{\bar{x}_n - \mu}{\sigma/\sqrt{n}} < 1.96) = 0.95
$$

To arrive at our desired confidence interval, we make take the inequality inside the probability operation and solve for $\mu$:

$$
\begin{aligned}
-1.96 < &\frac{\bar{x}_n - \mu}{\sigma/\sqrt{n}} < 1.96 \\
-1.96 \cdot \frac{\sigma}{\sqrt{n}} < & \bar{x}_n - \mu < 1.96 \cdot \frac{\sigma}{\sqrt{n}} \\
-\bar{x}_n - 1.96 \cdot \frac{\sigma}{\sqrt{n}} < &- \mu < -\bar{x}_n + 1.96 \cdot \frac{\sigma}{\sqrt{n}} \\
\bar{x}_n - 1.96 \cdot \frac{\sigma}{\sqrt{n}} < & \mu < \bar{x}_n + 1.96 \cdot \frac{\sigma}{\sqrt{n}}
\end{aligned}
$$

Therefore:

$$
P\Big(\bar{X}_n - 1.96 \cdot \frac{\sigma}{\sqrt{n}} < \mu < \bar{x}_n + 1.96 \cdot \frac{\sigma}{\sqrt{n}}\Big) = 0.95
$$

# Part (c)
We now assume that there is another I.I.D. sample $X_{n+1}, \dots, X_{2n}$ of size $n$, that is also independent of the first sample, and is from another Normal distribution $N(\mu, \tau^2)$. (We also assume that $\tau^2$ does **NOT** refer to the precision, but instead the variance of the second sample.)

Immediately, we can conclude that the sampling distribution of $\bar{X}_{2n}$ is yet another Normal distribution.